### ISSUE TITLE
Update `RecipeRun` model to match GitHub check runs API

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-orchestrator#13] opened 2022-01-10 14:59 UTC
So are we going to punt on this suggestion for now?

To be more explicit, here are all the fields from github check runs API:

Name | Type | In | Description
-- | -- | -- | --
accept | string | header | Setting to application/vnd.github.v3+json is recommended.
owner | string | path |  
repo | string | path |  
name | string | body | Required. The name of the check. For example, "code-coverage".
head_sha | string | body | Required. The SHA of the commit.
details_url | string | body | The URL of the integrator's site that has the full details of the check. If the integrator does not provide this, then the homepage of the GitHub app is used.
external_id | string | body | A reference for the run on the integrator's system.
status | string | body | The current status. Can be one of queued, in_progress, or completed.Default: queued
started_at | string | body | The time that the check run began. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
conclusion | string | body | Required if you provide completed_at or a status of completed. The final conclusion of the check. Can be one of action_required, cancelled, failure, neutral, success, skipped, stale, or timed_out. When the conclusion is action_required, additional details should be provided on the site specified by details_url.Note: Providing conclusion will automatically set the status parameter to completed. You cannot change a check run conclusion to stale, only GitHub can set this.
completed_at | string | body | The time the check completed. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
output | object | body | Check runs can accept a variety of data in the output object, including a title and summary and can optionally provide descriptive details about the run. See the output object description.

_Originally posted by @rabernat in https://github.com/pangeo-forge/pangeo-forge-orchestrator/pull/6#discussion_r777606967_

**Comment by rabernat** [comment] 2022-01-10 15:02
Duplicate of #8

**Closed by rabernat** 2022-01-10 15:02 UTC
